DEBUG = True

VALUE = 'Value from config.settings'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_REDIS_MAX_CONNECTIONS = 5

LOG_LEVEL = 'DEBUG'

SQLALCHEMY_TRACK_MODIFICATIONS = True